services:
  - type: web
    name: rag-customer-service
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 --timeout 120 -b 0.0.0.0:$PORT run:app
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production